package com.senac.oo.calculadora;

public class Calculadora extends javax.swing.JFrame {

    private String temp;
    private float n1, n2;
    private char operador;
    private final Calc calculadora = new Calc();

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    private void operacao(char op) throws NumberFormatException {
        // TODO add your handling code here:
        operador = op;
        n1 = Float.parseFloat(jtfCaixaDeTexto.getText());
        jtfCaixaDeTexto.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfCaixaDeTexto = new javax.swing.JTextField();
        jtbIgual = new javax.swing.JToggleButton();
        btn_number_1 = new javax.swing.JButton();
        btn_number_2 = new javax.swing.JButton();
        btn_number_3 = new javax.swing.JButton();
        btn_number_4 = new javax.swing.JButton();
        btn_number_5 = new javax.swing.JButton();
        btn_number_6 = new javax.swing.JButton();
        btn_number_7 = new javax.swing.JButton();
        btn_number_8 = new javax.swing.JButton();
        btn_number_9 = new javax.swing.JButton();
        btn_number_0 = new javax.swing.JButton();
        btn_ope_sub = new javax.swing.JButton();
        btn_ope_ponto = new javax.swing.JButton();
        btn_ope_mul = new javax.swing.JButton();
        btn_ope_clr = new javax.swing.JButton();
        btn_ope_div = new javax.swing.JButton();
        btn_ope_pot = new javax.swing.JButton();
        btn_ope_ce = new javax.swing.JButton();
        btn_ope_raiz = new javax.swing.JButton();
        btn_ope_soma = new javax.swing.JButton();
        btn_ope_maisoumenos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Calculadora");

        jtfCaixaDeTexto.setBackground(java.awt.SystemColor.menu);
        jtfCaixaDeTexto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtfCaixaDeTexto.setForeground(new java.awt.Color(255, 255, 255));
        jtfCaixaDeTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCaixaDeTextoActionPerformed(evt);
            }
        });

        jtbIgual.setText("=");
        jtbIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbIgualActionPerformed(evt);
            }
        });

        btn_number_1.setText("1");
        btn_number_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_number_1ActionPerformed(evt);
            }
        });

        btn_number_2.setText("2");
        btn_number_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_number_2ActionPerformed(evt);
            }
        });

        btn_number_3.setText("3");
        btn_number_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_number_3ActionPerformed(evt);
            }
        });

        btn_number_4.setText("4");
        btn_number_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_number_4ActionPerformed(evt);
            }
        });

        btn_number_5.setText("5");
        btn_number_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_number_5ActionPerformed(evt);
            }
        });

        btn_number_6.setText("6");
        btn_number_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_number_6ActionPerformed(evt);
            }
        });

        btn_number_7.setText("7");
        btn_number_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_number_7ActionPerformed(evt);
            }
        });

        btn_number_8.setText("8");
        btn_number_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_number_8ActionPerformed(evt);
            }
        });

        btn_number_9.setText("9");
        btn_number_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_number_9ActionPerformed(evt);
            }
        });

        btn_number_0.setText("0");
        btn_number_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_number_0ActionPerformed(evt);
            }
        });

        btn_ope_sub.setText("-");
        btn_ope_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ope_subActionPerformed(evt);
            }
        });

        btn_ope_ponto.setText(".");
        btn_ope_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ope_pontoActionPerformed(evt);
            }
        });

        btn_ope_mul.setText("*");
        btn_ope_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ope_mulActionPerformed(evt);
            }
        });

        btn_ope_clr.setText("Clr");
        btn_ope_clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ope_clrActionPerformed(evt);
            }
        });

        btn_ope_div.setText("/");
        btn_ope_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ope_divActionPerformed(evt);
            }
        });

        btn_ope_pot.setText("X²");
        btn_ope_pot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ope_potActionPerformed(evt);
            }
        });

        btn_ope_ce.setText("CE");
        btn_ope_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ope_ceActionPerformed(evt);
            }
        });

        btn_ope_raiz.setText(" √  ");
        btn_ope_raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ope_raizActionPerformed(evt);
            }
        });

        btn_ope_soma.setText("+");
        btn_ope_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ope_somaActionPerformed(evt);
            }
        });

        btn_ope_maisoumenos.setText("+/-");
        btn_ope_maisoumenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ope_maisoumenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_ope_raiz)
                            .addGap(18, 18, 18)
                            .addComponent(btn_ope_ce))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(366, 366, 366)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ope_div)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ope_mul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ope_sub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ope_soma))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_number_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_number_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_number_3)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ope_maisoumenos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_number_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_number_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_number_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ope_pot))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_number_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_number_8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_number_9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ope_ponto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_number_0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ope_clr))
                    .addComponent(jtfCaixaDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_number_0, btn_number_1, btn_number_2, btn_number_3, btn_number_4, btn_number_5, btn_number_6, btn_number_7, btn_number_8, btn_number_9, btn_ope_ce, btn_ope_clr, btn_ope_maisoumenos, btn_ope_ponto, btn_ope_pot, btn_ope_raiz});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCaixaDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ope_div)
                    .addComponent(btn_ope_mul)
                    .addComponent(btn_ope_sub)
                    .addComponent(btn_ope_soma)
                    .addComponent(btn_ope_raiz)
                    .addComponent(btn_ope_ce))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_number_1)
                    .addComponent(btn_number_2)
                    .addComponent(btn_number_3)
                    .addComponent(btn_ope_maisoumenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_number_4)
                    .addComponent(btn_number_5)
                    .addComponent(btn_number_6)
                    .addComponent(btn_ope_pot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_number_7)
                    .addComponent(btn_number_8)
                    .addComponent(btn_number_9)
                    .addComponent(btn_ope_ponto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_number_0)
                    .addComponent(jtbIgual)
                    .addComponent(btn_ope_clr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_number_0, btn_number_1, btn_number_2, btn_number_3, btn_number_4, btn_number_5, btn_number_6, btn_number_7, btn_number_8, btn_number_9, btn_ope_ce, btn_ope_clr, btn_ope_div, btn_ope_maisoumenos, btn_ope_mul, btn_ope_ponto, btn_ope_pot, btn_ope_raiz, btn_ope_soma, btn_ope_sub, jtbIgual});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCaixaDeTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCaixaDeTextoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfCaixaDeTextoActionPerformed

    private void jtbIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbIgualActionPerformed
        n2 = Float.parseFloat(jtfCaixaDeTexto.getText());
        float res;
        res = 0;
        switch (operador) {
            case '+':
                res = calculadora.soma(n1, n2);
                break;
            case '-':
                res = calculadora.menos(n1, n2);
                break;
            case '*':
                res = calculadora.mult(n1, n2);
                break;
            case '/':
                res = calculadora.divisao(n1, n2);
                break;
            case 'x':
                res = calculadora.potencia(n1, n2);
                break;

        }
        jtfCaixaDeTexto.setText(String.valueOf(res));
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbIgualActionPerformed

    private void btn_number_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_number_1ActionPerformed
        btn('1');

    }//GEN-LAST:event_btn_number_1ActionPerformed

    private void btn_number_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_number_2ActionPerformed
        btn('2');        // TODO add your handling code here:
    }//GEN-LAST:event_btn_number_2ActionPerformed

    private void btn_number_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_number_3ActionPerformed
        btn('3');
    }//GEN-LAST:event_btn_number_3ActionPerformed

    private void btn_number_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_number_4ActionPerformed
        btn('4');
    }//GEN-LAST:event_btn_number_4ActionPerformed

    private void btn_number_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_number_5ActionPerformed
        btn('5');
    }//GEN-LAST:event_btn_number_5ActionPerformed

    private void btn_number_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_number_6ActionPerformed
        btn('6');
    }//GEN-LAST:event_btn_number_6ActionPerformed

    private void btn_number_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_number_7ActionPerformed
        btn('7');
    }//GEN-LAST:event_btn_number_7ActionPerformed

    private void btn_number_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_number_8ActionPerformed
        btn('8');
    }//GEN-LAST:event_btn_number_8ActionPerformed

    private void btn_number_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_number_9ActionPerformed
        btn('9');
    }//GEN-LAST:event_btn_number_9ActionPerformed

    private void btn_number_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_number_0ActionPerformed
        btn('0');
    }//GEN-LAST:event_btn_number_0ActionPerformed

    private void btn_ope_raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ope_raizActionPerformed
        n1 = Float.parseFloat(jtfCaixaDeTexto.getText());
        float x = n1;

        jtfCaixaDeTexto.setText(String.valueOf(Math.sqrt(x)));
        n1 = 0;
        n2 = 0;
    }//GEN-LAST:event_btn_ope_raizActionPerformed

    private void btn_ope_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ope_somaActionPerformed
        operacao('+');
    }//GEN-LAST:event_btn_ope_somaActionPerformed

    private void btn_ope_maisoumenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ope_maisoumenosActionPerformed
        n1 = Float.parseFloat(jtfCaixaDeTexto.getText());
        // float x=n1;
        if (n1 > 0) {
            n1 = n1 - (n1 + n1);
            jtfCaixaDeTexto.setText(String.valueOf(n1));
        }
    }//GEN-LAST:event_btn_ope_maisoumenosActionPerformed

    private void btn_ope_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ope_subActionPerformed
        operacao('-');
    }//GEN-LAST:event_btn_ope_subActionPerformed

    private void btn_ope_pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ope_pontoActionPerformed
        btn('.');
    }//GEN-LAST:event_btn_ope_pontoActionPerformed

    private void btn_ope_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ope_mulActionPerformed
        operacao('*');
    }//GEN-LAST:event_btn_ope_mulActionPerformed

    private void btn_ope_clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ope_clrActionPerformed
        n1 = 0;
        n2 = 0;
        jtfCaixaDeTexto.setText("");
    }//GEN-LAST:event_btn_ope_clrActionPerformed

    private void btn_ope_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ope_divActionPerformed
        operacao('/');
    }//GEN-LAST:event_btn_ope_divActionPerformed

    private void btn_ope_potActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ope_potActionPerformed
        operacao('x');
    }//GEN-LAST:event_btn_ope_potActionPerformed

    private void btn_ope_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ope_ceActionPerformed
        jtfCaixaDeTexto.setText("");
    }//GEN-LAST:event_btn_ope_ceActionPerformed
    private void btn(char num) {
        // TODO add your handling code here:
        temp = jtfCaixaDeTexto.getText();
        temp = temp + num;
        jtfCaixaDeTexto.setText(temp);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_number_0;
    private javax.swing.JButton btn_number_1;
    private javax.swing.JButton btn_number_2;
    private javax.swing.JButton btn_number_3;
    private javax.swing.JButton btn_number_4;
    private javax.swing.JButton btn_number_5;
    private javax.swing.JButton btn_number_6;
    private javax.swing.JButton btn_number_7;
    private javax.swing.JButton btn_number_8;
    private javax.swing.JButton btn_number_9;
    private javax.swing.JButton btn_ope_ce;
    private javax.swing.JButton btn_ope_clr;
    private javax.swing.JButton btn_ope_div;
    private javax.swing.JButton btn_ope_maisoumenos;
    private javax.swing.JButton btn_ope_mul;
    private javax.swing.JButton btn_ope_ponto;
    private javax.swing.JButton btn_ope_pot;
    private javax.swing.JButton btn_ope_raiz;
    private javax.swing.JButton btn_ope_soma;
    private javax.swing.JButton btn_ope_sub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jtbIgual;
    private javax.swing.JTextField jtfCaixaDeTexto;
    // End of variables declaration//GEN-END:variables
}
